import cryptanalib as ca

d = 8276730537354063873046700086606934013390657907137764360442957114148983703392213920905379521933961200662349418726972470589061811064510563973168097131091762900935884000158700608857487894152877574467022635471921054922438416372847738044720341171693728509510304733152582025735997457366640962042446371702796650429270558556364971206673220641102736535785495085270088144553219777365472362543536538109527913412532336001148762959211359919986044869355021796538441331705044929239323402165504467704827987337504638532978042282749691349759655331384162387839085847376059025035741851624666333548281288846373129193232087364721195558785

N = 10582801803234222023721351326204905463469321586937873866285899804705438289550794516434678042160644904163578778193959630189545495390487529871810472562828953980775617092992054819000569379567214328036625223601593768074993103126020801627845266883277896935534900134552457628778290646235319742652095517837642111737039755900571013123362947713434696280050067990761280634722593133366154815295209776044603345322953117132250103892984014819690279192133597065661729463436631976729813726128619125291814410455706189604700693994757946995645898522397403679829590407298131095142520403589090633192841184074504222946814847796446760184239L

e = 0x10001

badsig = 8864006670929406852925128423419283000101606264931546544565004118285111530579411512945707908758302944358049245159881240365195456784997978690049780123607312704598614883100338341770324555702622215028874055295233188087028972047396168538381606028425952850084870840815139465808335221537979841948906784351532564396334588129879467099436972117704102514869368975631607984728653576512470131900790248497082055162110680555834874277167971776484142044468048689414584647613377242581544618782866426893967031773962301853433165727478082390333355401924553292504003746966703113454750999893154821514523123639279610673613179496062870087972L

message = 2

print 'Testing RSA-CRT fault attack...'
try:
   assert(ca.rsa_crt_fault_attack(badsig, message, N, verbose=True) == d)
except:
   exit('RSA-CRT fault attack is broken!')
